services:
  web:
    build: ./BACK/
    container_name: django_backend
    command: >
      python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=WF
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - CORS_ALLOWED_ORIGINS=http://localhost:4000,http://angular-app:4000
    volumes:
      - ./BACK:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - angular-app
    networks:
      - backend
      - frontend

  angular-app:
    build: ./FRONT/my-proyecto-app/
    container_name: angular_frontend
    ports:
      - "4000:4000"
    environment:
      - API_URL=http://web:8000
    networks:
      - frontend
      - backend

networks:
  backend:
    external: true
  frontend:
    driver: bridge
